mutation {
  createCredential(
    data: {
      appName: "Appointment Scheduler"
      clientId: "1089282576141-mv6t45022af9o865qmnr9g7qsov2asb6.apps.googleusercontent.com"
      clientSecret: "ENTER-CLIENT-SECRET-HERE"
      token: {
        create: {
          access_token: "ACCESS-TOKEN-HERE"
          refresh_token: "REFRESH-TOKEN-HERE"
          scope: ["https://www.googleapis.com/auth/calendar.readonly"]
          token_type: "Bearer"
          expiry_date: "1610146384590"
        }
      }
    }
  ) {
    _id
    appName
    clientId
    clientSecret
    token{data{access_token}}
  }
}