mutation {
  createCredential(
    data: {
      credentialId: "Appointment Scheduler dummy1"
      appName: "Appointment Scheduler"
      clientId: "1089282576141-mv6t45022af9o865qmnr9g7qsov2asb6.apps.googleusercontent.com"
      clientSecret: "ENTER-CLIENT-SECRET-HERE"
      accessToken: "ACCESS-TOKEN-HERE"
      refreshToken: "REFRESH-TOKEN-HERE"
      scope: ["https://www.googleapis.com/auth/calendar.readonly"]
      tokenType: "Bearer"
      expiryDate: "1610146384590"
    }
  ) {
    _id
    credentialId
    appName
    clientId
    clientSecret
    access_token : accessToken
    refresh_token : refreshToken
  }
}